### ISSUE TITLE
Flashlight problems

### ISSUE THREAD

**Issue by CharlesBeise** [CharlesBeise/ScaryAttic#93]
When we swap out one flashlight for the next stage of the flashlight, it isn't being recognized by our verbs. Probably need a helper function similar to identifyPolaroid

![image](https://user-images.githubusercontent.com/81447311/202765470-68ec2704-dfd3-4498-b4cc-1da1d2a9197e.png)

**Comment by CharlesBeise** [comment]
I can work on this eventually, I just wanted to make note of it so I don't forget.

**Comment by SaphiraSkies** [comment]
Should be fixed with PR #100
