### ISSUE TITLE
Battery conditional

### ISSUE THREAD

**Issue by CharlesBeise** [CharlesBeise/ScaryAttic#94]
Upon entering the second bedroom, the player can "examine" the battery before it is unlocked:

![image](https://user-images.githubusercontent.com/81447311/202766739-2916758d-4916-447f-a224-5df60d91522a.png)

**Comment by SaphiraSkies** [comment]
I will be fixing this.

**Comment by SaphiraSkies** [comment]
Fixed in PR #98
